version: '3.8'

services:
  postgres:
    image: postgres
    hostname: test.postgres.com
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/host/
      - ./docker/postgres/init/:/docker-entrypoint-initdb.d/
  postgres_scram:
    image: postgres
    hostname: test.postgres_scram.com
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./docker/postgres_scram/data/:/var/lib/postgresql/host/
      - ./docker/postgres_scram/init/:/docker-entrypoint-initdb.d/
  tests:
    build: .
    depends_on:
      - postgres
      - postgres_scram
    environment:
      - WAIT_HOSTS=test.postgres.com:5432,test.postgres_scram.com:5432
      # Wait thirty seconds after database goes online
      # For database metadata initialization
      - WAIT_AFTER_HOSTS=15
